apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- route.yaml
- service.yaml
- namespace.yaml
images:
- digest: sha256:1750fb38a0f24baf9a750ba017fb357882fed31f9fe6c5710e82712022b65744
  name: quay.io/sachinayyar/tekton-argo
  newName: quay.io/sachinayyar/tekton-argo:latest
