apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- route.yaml
- service.yaml
- namespace.yaml
images:
- digest: sha256:d646fabc4cd01d3d657d2222a554628120c1c7b0bb16cb09bf9896fb40e028f6
  name: quay.io/sachinayyar/tekton-argo
  newName: quay.io/sachinayyar/tekton-argo
