apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- route.yaml
- service.yaml
- namespace.yaml
images:
- digest: sha256:9077586e9c7b4acefc8bd1430e4e64b5e5e6a40798d50962b9dd4afba0cdf0a8
  name: quay.io/sachinayyar/tekton-argo
  newName: quay.io/sachinayyar/tekton-argo:latest
