apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- route.yaml
- service.yaml
- namespace.yaml
images:
- digest: sha256:a6c641eb3d4b532b8532e88eca9f10343e46b6d86ca3c55a36767b422debfcca
  name: quay.io/sachinayyar/tekton-argo
  newName: quay.io/sachinayyar/tekton-argo
