apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- route.yaml
- service.yaml
- namespace.yaml
images:
- digest: sha256:4504148075dab0f0b02ffda699141cf117cef584bcc7b73bf8120033f0214777
  name: quay.io/sachinayyar/tekton-argo
  newName: quay.io/sachinayyar/tekton-argo
